#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  6 15:48:50 2016

@author: andrewalferman
"""

import numpy as np

# a = [[0,-1,-1,-1,-1],[-1,0,1,2,3],[2,0,-1,-4,-9],[-3,0,1,8,27],[4,0,-1,-16,-81]]
# b = [0,-1,0,0,0]
a = [[-1, -1, -1], [0, 1, 2], [0, -1/2, -2]]
b = [0, 0, -1]

print(np.linalg.solve(a, b))
