#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 24 21:42:59 2016

@author: andrewalferman
"""
import numpy as np

x = [0.0, 1.5, 3.0]


def f(x):
    return x**3.0 - 4.0*x**2 + 3.0*x + 1.0


def fp(x):
    return 3.0*x**2.0 - 8.0*x + 3.0

iters = x

for k in range(20):
    for l in x:
        xnew = x - f(x)/fp(x)
    iters.append(xnew)
    if np.max(np.abs((xnew-x) / x)) < 0.01:
        break
    x = xnew

print(x)