#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 18 22:36:46 2016

@author: andrewalferman
"""

import numpy as np

t = np.pi / 6
a = np.exp(t * 1j)
b = np.cos(t) + 1j * np.sin(t)

print(a, b)
print(1j)
